# Generated by Django 5.0.7 on 2024-07-16 07:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Apartment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "water_payment",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "area_payment",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (0, "Январь"),
                            (1, "Февраль"),
                            (2, "Март"),
                            (3, "Апрель"),
                            (4, "Май"),
                            (5, "Июнь"),
                            (6, "Июль"),
                            (7, "Август"),
                            (8, "Сентябрь"),
                            (9, "Октябрь"),
                            (10, "Ноябрь"),
                            (11, "Декабрь"),
                        ]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)]
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="Apartment.apartment",
                    ),
                ),
            ],
            options={
                "unique_together": {("apartment", "month", "year")},
            },
        ),
    ]
