# Generated by Django 5.0.7 on 2024-07-16 07:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Apartment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterMeter",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("mark", models.TextField(blank=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_meters",
                        to="Apartment.apartment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterMeterHistory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (0, "Январь"),
                            (1, "Февраль"),
                            (2, "Март"),
                            (3, "Апрель"),
                            (4, "Май"),
                            (5, "Июнь"),
                            (6, "Июль"),
                            (7, "Август"),
                            (8, "Сентябрь"),
                            (9, "Октябрь"),
                            (10, "Ноябрь"),
                            (11, "Декабрь"),
                        ]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)]
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="WaterMeter.watermeter",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Water meter histories",
                "unique_together": {("meter", "month", "year")},
            },
        ),
    ]
